### ISSUE TITLE
The training time is too long!!!!

### ISSUE THREAD

**Issue by LLM4Rec** [chenyuxin1999/S-DPO#3]
SFT needs 40h for one epoch! 
The time spent on training is indeed too long!!!!

**Comment by chenyuxin1999** [comment]
Hi @LLM4Rec ,
Thank you for your interest in our work.

The training time for SFT largely depends on the number and type of GPUs being used. In the era of large models, the demand for computational power is unavoidable. If you have any other questions or concerns, please feel free to reach out.

**Comment by LLM4Rec** [comment]
Thanks for your quick response!
I would like to know how much time it took for your 4 cards during 5 epochs in SFT and 3 epochs in S-DPO, respectively?

**Comment by chenyuxin1999** [comment]
On four NVIDIA RTX A5000 GPUs, running SFT on the LastFM dataset for five epochs takes approximately 6 hours, while running DPO for three epochs takes around 9 hours. The exact time may vary depending on hyperparameter settings, such as the frequency of evaluation.

**Comment by LLM4Rec** [comment]
I have a question: whether it's on 40G or 80G, you can increase the batch size to accelerate training. Why do you choose such a small batch size?

**Comment by chenyuxin1999** [comment]
Hi @LLM4Rec,

You’re absolutely right—the hyperparameters in the code are provided as examples and don’t reflect the exact training settings in our environment. Please feel free to adjust them as needed.

**Comment by LLM4Rec** [comment]
Thank you for your patient response. I look forward to your complete data processing scripts to help me learn and follow your work to make improvements.

**Comment by LLM4Rec** [comment]
@chenyuxin1999 I reproduced the results of lastfm. However, I found that directly using SFT can surpass all baselines, and there's no need for DPO or S-DPO.

**Comment by chenyuxin1999** [comment]
Hi @LLM4Rec,
Thank you for your feedback! To discuss the experimental details and specific results further without making this issue too lengthy, would you mind sharing an email address? This way, we can have a more detailed conversation. Thanks!

**Comment by KlaineWei** [comment]
> @chenyuxin1999 I reproduced the results of lastfm. However, I found that directly using SFT can surpass all baselines, and there's no need for DPO or S-DPO.

Could you please share your detailed parameters? I just reproduced the results but  found them much lower than baselines, and the dpo or sdpo method doesn't make any improvement to the sft result.

**Comment by Mistsink** [comment]
> [@chenyuxin1999](https://github.com/chenyuxin1999) I reproduced the results of lastfm. However, I found that directly using SFT can surpass all baselines, and there's no need for DPO or S-DPO.

Hello, could you please share the experimental parameters you used? I am having trouble reproducing the results of this work. With the same configuration, my result on the LastFM dataset is only 0.61. My email is [fireworkhy@gmail.com](mailto:fireworkhy@gmail.com). Thank you very much!

**Comment by Mistsink** [comment]
> > [@chenyuxin1999](https://github.com/chenyuxin1999) I reproduced the results of lastfm. However, I found that directly using SFT can surpass all baselines, and there's no need for DPO or S-DPO.
> 
> Could you please share your detailed parameters? I just reproduced the results but found them much lower than baselines, and the dpo or sdpo method doesn't make any improvement to the sft result.

Hello, have you managed to solve this issue? If it’s convenient for you, you can also contact me by email at fireworkhy@gmail.com.

**Comment by zwjuer** [comment]
> > [@chenyuxin1999](https://github.com/chenyuxin1999) I reproduced the results of lastfm. However, I found that directly using SFT can surpass all baselines, and there's no need for DPO or S-DPO.
> 
> Hello, could you please share the experimental parameters you used? I am having trouble reproducing the results of this work. With the same configuration, my result on the LastFM dataset is only 0.61. My email is [fireworkhy@gmail.com](mailto:fireworkhy@gmail.com). Thank you very much!

Hello, could you please share the experimental parameters you used? I am having trouble reproducing the results of this work. With the same configuration, my result on the LastFM dataset is only 0.53. My email is [18130792993@163.com]. Thank you very much!
